#
# SPDX-FileCopyrightText: Â© 2020-2024 Serpent OS Developers
#
# SPDX-License-Identifier: MPL-2.0
#
name        : docker-compose
version     : "5.1.0"
release     : 15
homepage    : https://github.com/docker/compose
upstreams   :
    - https://github.com/docker/compose/archive/refs/tags/v5.1.0.tar.gz : 61ffbd8e8461dfebbb1c2e195f96b372a5bbc9343e6c1ba01184c3d630150a78
summary     : Define and run multi-container applications with Docker 
description : |
    Define and run multi-container applications with Docker 
license     :
    - Apache-2.0
networking  : true
builddeps   :
    - binary(git)
    - binary(go)
rundeps     :
    - binary(docker)
environment : |
    export _compose_r=github.com/docker/compose
    export _cli_plugins_dir=%(libdir)/docker/cli-plugins
setup      : |
    go mod vendor
build      : |
    export GO111MODULE=auto

    export CGO_CFLAGS="${CFLAGS}"
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external -ldflags=-X=${_compose_r}/v2/internal.Version=v%(version)"

    # Git commit corresponding to the version tag
    export GITCOMMIT=$(git ls-remote https://github.com/docker/compose.git refs/tags/v%(version) |awk '{print $1}')

    go build -trimpath -tags "e2e,kube" -o docker-compose ./cmd
install    : |
    %install_exe docker-compose -t %(installroot)${_cli_plugins_dir}/

    # Compatibility symlink
    %install_dir %(installroot)%(bindir)
    ln -srv %(installroot)/${_cli_plugins_dir}/docker-compose %(installroot)%(bindir)/docker-compose
